backend:
  name: git-gateway
  branch: main

media_folder: "content/images"
public_folder: "/images"

collections:
  - name: "posts"
    label: "Posts"
    folder: "content"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Título", name: "title", widget: "string"}
      - {label: "Data", name: "date", widget: "datetime"}
      - {label: "Resumo", name: "summary", widget: "text"}
      - {label: "Corpo", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}
